# Site settings
title: Brainhack Western France 2019
email: brainhack@inria.fr
description: 2-day workshop on November 14-15th at IRISA/Inria Rennes
baseurl: "/" # the subpath of your site, e.g. /blog/
url: "https://brainhack.irisa.fr" # the base hostname & protocol for your site

background-image: /img/banner.jpg

twitter_username:
github_username: inria-visages

# Build settings
markdown: kramdown
